<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CountryModel;

class countrymasterseeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CountryModel::truncate();
        $countries = array(
        array('id' => 1,'flagicon' => 'AF' ,'countryname'=> "Afghanistan",'phonecode' => 93),
        array('id' => 2,'flagicon' => 'AL' ,'countryname'=> "Albania",'phonecode' => 355),
        array('id' => 3,'flagicon' => 'DZ' ,'countryname'=> "Algeria",'phonecode' => 213),
        array('id' => 4,'flagicon' => 'AS' ,'countryname'=> "American Samoa",'phonecode' => 1684),
        array('id' => 5,'flagicon' => 'AD' ,'countryname'=> "Andorra",'phonecode' => 376),
        array('id' => 6,'flagicon' => 'AO' ,'countryname'=> "Angola",'phonecode' => 244),
        array('id' => 7,'flagicon' => 'AI' ,'countryname'=> "Anguilla",'phonecode' => 1264),
        array('id' => 8,'flagicon' => 'AQ' ,'countryname'=> "Antarctica",'phonecode' => 0),
        array('id' => 9,'flagicon' => 'AG' ,'countryname'=> "Antigua And Barbuda",'phonecode' => 1268),
        array('id' => 10,'flagicon' => 'AR','countryname'=> "Argentina",'phonecode' => 54),
        array('id' => 11,'flagicon' => 'AM','countryname'=> "Armenia",'phonecode' => 374),
        array('id' => 12,'flagicon' => 'AW','countryname'=> "Aruba",'phonecode' => 297),
        array('id' => 13,'flagicon' => 'AU','countryname'=> "Australia",'phonecode' => 61),
        array('id' => 14,'flagicon' => 'AT','countryname'=> "Austria",'phonecode' => 43),
        array('id' => 15,'flagicon' => 'AZ','countryname'=> "Azerbaijan",'phonecode' => 994),
        array('id' => 16,'flagicon' => 'BS','countryname'=> "Bahamas The",'phonecode' => 1242),
        array('id' => 17,'flagicon' => 'BH','countryname'=> "Bahrain",'phonecode' => 973),
        array('id' => 18,'flagicon' => 'BD','countryname'=> "Bangladesh",'phonecode' => 880),
        array('id' => 19,'flagicon' => 'BB','countryname'=> "Barbados",'phonecode' => 1246),
        array('id' => 20,'flagicon' => 'BY','countryname'=> "Belarus",'phonecode' => 375),
        array('id' => 21,'flagicon' => 'BE','countryname'=> "Belgium",'phonecode' => 32),
        array('id' => 22,'flagicon' => 'BZ','countryname'=> "Belize",'phonecode' => 501),
        array('id' => 23,'flagicon' => 'BJ','countryname'=> "Benin",'phonecode' => 229),
        array('id' => 24,'flagicon' => 'BM','countryname'=> "Bermuda",'phonecode' => 1441),
        array('id' => 25,'flagicon' => 'BT','countryname'=> "Bhutan",'phonecode' => 975),
        array('id' => 26,'flagicon' => 'BO','countryname'=> "Bolivia",'phonecode' => 591),
        array('id' => 27,'flagicon' => 'BA','countryname'=> "Bosnia and Herzegovina",'phonecode' => 387),
        array('id' => 28,'flagicon' => 'BW','countryname'=> "Botswana",'phonecode' => 267),
        array('id' => 29,'flagicon' => 'BV','countryname'=> "Bouvet Island",'phonecode' => 0),
        array('id' => 30,'flagicon' => 'BR','countryname'=> "Brazil",'phonecode' => 55),
        array('id' => 31,'flagicon' => 'IO','countryname'=> "British Indian Ocean Territory",'phonecode' => 246),
        array('id' => 32,'flagicon' => 'BN','countryname'=> "Brunei",'phonecode' => 673),
        array('id' => 33,'flagicon' => 'BG','countryname'=> "Bulgaria",'phonecode' => 359),
        array('id' => 34,'flagicon' => 'BF','countryname'=> "Burkina Faso",'phonecode' => 226),
        array('id' => 35,'flagicon' => 'BI','countryname'=> "Burundi",'phonecode' => 257),
        array('id' => 36,'flagicon' => 'KH','countryname'=> "Cambodia",'phonecode' => 855),
        array('id' => 37,'flagicon' => 'CM','countryname'=> "Cameroon",'phonecode' => 237),
        array('id' => 38,'flagicon' => 'CA','countryname'=> "Canada",'phonecode' => 1),
        array('id' => 39,'flagicon' => 'CV','countryname'=> "Cape Verde",'phonecode' => 238),
        array('id' => 40,'flagicon' => 'KY','countryname'=> "Cayman Islands",'phonecode' => 1345),
        array('id' => 41,'flagicon' => 'CF','countryname'=> "Central African Republic",'phonecode' => 236),
        array('id' => 42,'flagicon' => 'TD','countryname'=> "Chad",'phonecode' => 235),
        array('id' => 43,'flagicon' => 'CL','countryname'=> "Chile",'phonecode' => 56),
        array('id' => 44,'flagicon' => 'CN','countryname'=> "China",'phonecode' => 86),
        array('id' => 45,'flagicon' => 'CX','countryname'=> "Christmas Island",'phonecode' => 61),
        array('id' => 46,'flagicon' => 'CC','countryname'=> "Cocos (Keeling) Islands",'phonecode' => 672),
        array('id' => 47,'flagicon' => 'CO','countryname'=> "Colombia",'phonecode' => 57),
        array('id' => 48,'flagicon' => 'KM','countryname'=> "Comoros",'phonecode' => 269),
        array('id' => 49,'flagicon' => 'CG','countryname'=> "Congo",'phonecode' => 242),
        array('id' => 50,'flagicon' => 'CD','countryname'=> "Congo The Democratic Republic Of The",'phonecode' => 242),
        array('id' => 51,'flagicon' => 'CK','countryname'=> "Cook Islands",'phonecode' => 682),
        array('id' => 52,'flagicon' => 'CR','countryname'=> "Costa Rica",'phonecode' => 506),
        array('id' => 53,'flagicon' => 'CI','countryname'=> "Cote D Ivoire (Ivory Coast)",'phonecode' => 225),
        array('id' => 54,'flagicon' => 'HR','countryname'=> "Croatia (Hrvatska)",'phonecode' => 385),
        array('id' => 55,'flagicon' => 'CU','countryname'=> "Cuba",'phonecode' => 53),
        array('id' => 56,'flagicon' => 'CY','countryname'=> "Cyprus",'phonecode' => 357),
        array('id' => 57,'flagicon' => 'CZ','countryname'=> "Czech Republic",'phonecode' => 420),
        array('id' => 58,'flagicon' => 'DK','countryname'=> "Denmark",'phonecode' => 45),
        array('id' => 59,'flagicon' => 'DJ','countryname'=> "Djibouti",'phonecode' => 253),
        array('id' => 60,'flagicon' => 'DM','countryname'=> "Dominica",'phonecode' => 1767),
        array('id' => 61,'flagicon' => 'DO','countryname'=> "Dominican Republic",'phonecode' => 1809),
        array('id' => 62,'flagicon' => 'TP','countryname'=> "East Timor",'phonecode' => 670),
        array('id' => 63,'flagicon' => 'EC','countryname'=> "Ecuador",'phonecode' => 593),
        array('id' => 64,'flagicon' => 'EG','countryname'=> "Egypt",'phonecode' => 20),
        array('id' => 65,'flagicon' => 'SV','countryname'=> "El Salvador",'phonecode' => 503),
        array('id' => 66,'flagicon' => 'GQ','countryname'=> "Equatorial Guinea",'phonecode' => 240),
        array('id' => 67,'flagicon' => 'ER','countryname'=> "Eritrea",'phonecode' => 291),
        array('id' => 68,'flagicon' => 'EE','countryname'=> "Estonia",'phonecode' => 372),
        array('id' => 69,'flagicon' => 'ET','countryname'=> "Ethiopia",'phonecode' => 251),
        array('id' => 70,'flagicon' => 'XA','countryname'=> "External Territories of Australia",'phonecode' => 61),
        array('id' => 71,'flagicon' => 'FK','countryname'=> "Falkland Islands",'phonecode' => 500),
        array('id' => 72,'flagicon' => 'FO','countryname'=> "Faroe Islands",'phonecode' => 298),
        array('id' => 73,'flagicon' => 'FJ','countryname'=> "Fiji Islands",'phonecode' => 679),
        array('id' => 74,'flagicon' => 'FI','countryname'=> "Finland",'phonecode' => 358),
        array('id' => 75,'flagicon' => 'FR','countryname'=> "France",'phonecode' => 33),
        array('id' => 76,'flagicon' => 'GF','countryname'=> "French Guiana",'phonecode' => 594),
        array('id' => 77,'flagicon' => 'PF','countryname'=> "French Polynesia",'phonecode' => 689),
        array('id' => 78,'flagicon' => 'TF','countryname'=> "French Southern Territories",'phonecode' => 0),
        array('id' => 79,'flagicon' => 'GA','countryname'=> "Gabon",'phonecode' => 241),
        array('id' => 80,'flagicon' => 'GM','countryname'=> "Gambia The",'phonecode' => 220),
        array('id' => 81,'flagicon' => 'GE','countryname'=> "Georgia",'phonecode' => 995),
        array('id' => 82,'flagicon' => 'DE','countryname'=> "Germany",'phonecode' => 49),
        array('id' => 83,'flagicon' => 'GH','countryname'=> "Ghana",'phonecode' => 233),
        array('id' => 84,'flagicon' => 'GI','countryname'=> "Gibraltar",'phonecode' => 350),
        array('id' => 85,'flagicon' => 'GR','countryname'=> "Greece",'phonecode' => 30),
        array('id' => 86,'flagicon' => 'GL','countryname'=> "Greenland",'phonecode' => 299),
        array('id' => 87,'flagicon' => 'GD','countryname'=> "Grenada",'phonecode' => 1473),
        array('id' => 88,'flagicon' => 'GP','countryname'=> "Guadeloupe",'phonecode' => 590),
        array('id' => 89,'flagicon' => 'GU','countryname'=> "Guam",'phonecode' => 1671),
        array('id' => 90,'flagicon' => 'GT','countryname'=> "Guatemala",'phonecode' => 502),
        array('id' => 91,'flagicon' => 'XU','countryname'=> "Guernsey and Alderney",'phonecode' => 44),
        array('id' => 92,'flagicon' => 'GN','countryname'=> "Guinea",'phonecode' => 224),
        array('id' => 93,'flagicon' => 'GW','countryname'=> "Guinea-Bissau",'phonecode' => 245),
        array('id' => 94,'flagicon' => 'GY','countryname'=> "Guyana",'phonecode' => 592),
        array('id' => 95,'flagicon' => 'HT','countryname'=> "Haiti",'phonecode' => 509),
        array('id' => 96,'flagicon' => 'HM','countryname'=> "Heard and McDonald Islands",'phonecode' => 0),
        array('id' => 97,'flagicon' => 'HN','countryname'=> "Honduras",'phonecode' => 504),
        array('id' => 98,'flagicon' => 'HK','countryname'=> "Hong Kong S.A.R.",'phonecode' => 852),
        array('id' => 99,'flagicon' => 'HU','countryname'=> "Hungary",'phonecode' => 36),
        array('id' => 100,'flagicon' => 'IS','countryname'=> "Iceland",'phonecode' => 354),
        array('id' => 101,'flagicon' => 'IN','countryname'=> "India",'phonecode' => 91),
        array('id' => 102,'flagicon' => 'ID','countryname'=> "Indonesia",'phonecode' => 62),
        array('id' => 103,'flagicon' => 'IR','countryname'=> "Iran",'phonecode' => 98),
        array('id' => 104,'flagicon' => 'IQ','countryname'=> "Iraq",'phonecode' => 964),
        array('id' => 105,'flagicon' => 'IE','countryname'=> "Ireland",'phonecode' => 353),
        array('id' => 106,'flagicon' => 'IL','countryname'=> "Israel",'phonecode' => 972),
        array('id' => 107,'flagicon' => 'IT','countryname'=> "Italy",'phonecode' => 39),
        array('id' => 108,'flagicon' => 'JM','countryname'=> "Jamaica",'phonecode' => 1876),
        array('id' => 109,'flagicon' => 'JP','countryname'=> "Japan",'phonecode' => 81),
        array('id' => 110,'flagicon' => 'XJ','countryname'=> "Jersey",'phonecode' => 44),
        array('id' => 111,'flagicon' => 'JO','countryname'=> "Jordan",'phonecode' => 962),
        array('id' => 112,'flagicon' => 'KZ','countryname'=> "Kazakhstan",'phonecode' => 7),
        array('id' => 113,'flagicon' => 'KE','countryname'=> "Kenya",'phonecode' => 254),
        array('id' => 114,'flagicon' => 'KI','countryname'=> "Kiribati",'phonecode' => 686),
        array('id' => 115,'flagicon' => 'KP','countryname'=> "Korea North",'phonecode' => 850),
        array('id' => 116,'flagicon' => 'KR','countryname'=> "Korea South",'phonecode' => 82),
        array('id' => 117,'flagicon' => 'KW','countryname'=> "Kuwait",'phonecode' => 965),
        array('id' => 118,'flagicon' => 'KG','countryname'=> "Kyrgyzstan",'phonecode' => 996),
        array('id' => 119,'flagicon' => 'LA','countryname'=> "Laos",'phonecode' => 856),
        array('id' => 120,'flagicon' => 'LV','countryname'=> "Latvia",'phonecode' => 371),
        array('id' => 121,'flagicon' => 'LB','countryname'=> "Lebanon",'phonecode' => 961),
        array('id' => 122,'flagicon' => 'LS','countryname'=> "Lesotho",'phonecode' => 266),
        array('id' => 123,'flagicon' => 'LR','countryname'=> "Liberia",'phonecode' => 231),
        array('id' => 124,'flagicon' => 'LY','countryname'=> "Libya",'phonecode' => 218),
        array('id' => 125,'flagicon' => 'LI','countryname'=> "Liechtenstein",'phonecode' => 423),
        array('id' => 126,'flagicon' => 'LT','countryname'=> "Lithuania",'phonecode' => 370),
        array('id' => 127,'flagicon' => 'LU','countryname'=> "Luxembourg",'phonecode' => 352),
        array('id' => 128,'flagicon' => 'MO','countryname'=> "Macau S.A.R.",'phonecode' => 853),
        array('id' => 129,'flagicon' => 'MK','countryname'=> "Macedonia",'phonecode' => 389),
        array('id' => 130,'flagicon' => 'MG','countryname'=> "Madagascar",'phonecode' => 261),
        array('id' => 131,'flagicon' => 'MW','countryname'=> "Malawi",'phonecode' => 265),
        array('id' => 132,'flagicon' => 'MY','countryname'=> "Malaysia",'phonecode' => 60),
        array('id' => 133,'flagicon' => 'MV','countryname'=> "Maldives",'phonecode' => 960),
        array('id' => 134,'flagicon' => 'ML','countryname'=> "Mali",'phonecode' => 223),
        array('id' => 135,'flagicon' => 'MT','countryname'=> "Malta",'phonecode' => 356),
        array('id' => 136,'flagicon' => 'XM','countryname'=> "Man (Isle of)",'phonecode' => 44),
        array('id' => 137,'flagicon' => 'MH','countryname'=> "Marshall Islands",'phonecode' => 692),
        array('id' => 138,'flagicon' => 'MQ','countryname'=> "Martinique",'phonecode' => 596),
        array('id' => 139,'flagicon' => 'MR','countryname'=> "Mauritania",'phonecode' => 222),
        array('id' => 140,'flagicon' => 'MU','countryname'=> "Mauritius",'phonecode' => 230),
        array('id' => 141,'flagicon' => 'YT','countryname'=> "Mayotte",'phonecode' => 269),
        array('id' => 142,'flagicon' => 'MX','countryname'=> "Mexico",'phonecode' => 52),
        array('id' => 143,'flagicon' => 'FM','countryname'=> "Micronesia",'phonecode' => 691),
        array('id' => 144,'flagicon' => 'MD','countryname'=> "Moldova",'phonecode' => 373),
        array('id' => 145,'flagicon' => 'MC','countryname'=> "Monaco",'phonecode' => 377),
        array('id' => 146,'flagicon' => 'MN','countryname'=> "Mongolia",'phonecode' => 976),
        array('id' => 147,'flagicon' => 'MS','countryname'=> "Montserrat",'phonecode' => 1664),
        array('id' => 148,'flagicon' => 'MA','countryname'=> "Morocco",'phonecode' => 212),
        array('id' => 149,'flagicon' => 'MZ','countryname'=> "Mozambique",'phonecode' => 258),
        array('id' => 150,'flagicon' => 'MM','countryname'=> "Myanmar",'phonecode' => 95),
        array('id' => 151,'flagicon' => 'NA','countryname'=> "Namibia",'phonecode' => 264),
        array('id' => 152,'flagicon' => 'NR','countryname'=> "Nauru",'phonecode' => 674),
        array('id' => 153,'flagicon' => 'NP','countryname'=> "Nepal",'phonecode' => 977),
        array('id' => 154,'flagicon' => 'AN','countryname'=> "Netherlands Antilles",'phonecode' => 599),
        array('id' => 155,'flagicon' => 'NL','countryname'=> "Netherlands The",'phonecode' => 31),
        array('id' => 156,'flagicon' => 'NC','countryname'=> "New Caledonia",'phonecode' => 687),
        array('id' => 157,'flagicon' => 'NZ','countryname'=> "New Zealand",'phonecode' => 64),
        array('id' => 158,'flagicon' => 'NI','countryname'=> "Nicaragua",'phonecode' => 505),
        array('id' => 159,'flagicon' => 'NE','countryname'=> "Niger",'phonecode' => 227),
        array('id' => 160,'flagicon' => 'NG','countryname'=> "Nigeria",'phonecode' => 234),
        array('id' => 161,'flagicon' => 'NU','countryname'=> "Niue",'phonecode' => 683),
        array('id' => 162,'flagicon' => 'NF','countryname'=> "Norfolk Island",'phonecode' => 672),
        array('id' => 163,'flagicon' => 'MP','countryname'=> "Northern Mariana Islands",'phonecode' => 1670),
        array('id' => 164,'flagicon' => 'NO','countryname'=> "Norway",'phonecode' => 47),
        array('id' => 165,'flagicon' => 'OM','countryname'=> "Oman",'phonecode' => 968),
        array('id' => 166,'flagicon' => 'PK','countryname'=> "Pakistan",'phonecode' => 92),
        array('id' => 167,'flagicon' => 'PW','countryname'=> "Palau",'phonecode' => 680),
        array('id' => 168,'flagicon' => 'PS','countryname'=> "Palestinian Territory Occupied",'phonecode' => 970),
        array('id' => 169,'flagicon' => 'PA','countryname'=> "Panama",'phonecode' => 507),
        array('id' => 170,'flagicon' => 'PG','countryname'=> "Papua new Guinea",'phonecode' => 675),
        array('id' => 171,'flagicon' => 'PY','countryname'=> "Paraguay",'phonecode' => 595),
        array('id' => 172,'flagicon' => 'PE','countryname'=> "Peru",'phonecode' => 51),
        array('id' => 173,'flagicon' => 'PH','countryname'=> "Philippines",'phonecode' => 63),
        array('id' => 174,'flagicon' => 'PN','countryname'=> "Pitcairn Island",'phonecode' => 0),
        array('id' => 175,'flagicon' => 'PL','countryname'=> "Poland",'phonecode' => 48),
        array('id' => 176,'flagicon' => 'PT','countryname'=> "Portugal",'phonecode' => 351),
        array('id' => 177,'flagicon' => 'PR','countryname'=> "Puerto Rico",'phonecode' => 1787),
        array('id' => 178,'flagicon' => 'QA','countryname'=> "Qatar",'phonecode' => 974),
        array('id' => 179,'flagicon' => 'RE','countryname'=> "Reunion",'phonecode' => 262),
        array('id' => 180,'flagicon' => 'RO','countryname'=> "Romania",'phonecode' => 40),
        array('id' => 181,'flagicon' => 'RU','countryname'=> "Russia",'phonecode' => 70),
        array('id' => 182,'flagicon' => 'RW','countryname'=> "Rwanda",'phonecode' => 250),
        array('id' => 183,'flagicon' => 'SH','countryname'=> "Saint Helena",'phonecode' => 290),
        array('id' => 184,'flagicon' => 'KN','countryname'=> "Saint Kitts And Nevis",'phonecode' => 1869),
        array('id' => 185,'flagicon' => 'LC','countryname'=> "Saint Lucia",'phonecode' => 1758),
        array('id' => 186,'flagicon' => 'PM','countryname'=> "Saint Pierre and Miquelon",'phonecode' => 508),
        array('id' => 187,'flagicon' => 'VC','countryname'=> "Saint Vincent And The Grenadines",'phonecode' => 1784),
        array('id' => 188,'flagicon' => 'WS','countryname'=> "Samoa",'phonecode' => 684),
        array('id' => 189,'flagicon' => 'SM','countryname'=> "San Marino",'phonecode' => 378),
        array('id' => 190,'flagicon' => 'ST','countryname'=> "Sao Tome and Principe",'phonecode' => 239),
        array('id' => 191,'flagicon' => 'SA','countryname'=> "Saudi Arabia",'phonecode' => 966),
        array('id' => 192,'flagicon' => 'SN','countryname'=> "Senegal",'phonecode' => 221),
        array('id' => 193,'flagicon' => 'RS','countryname'=> "Serbia",'phonecode' => 381),
        array('id' => 194,'flagicon' => 'SC','countryname'=> "Seychelles",'phonecode' => 248),
        array('id' => 195,'flagicon' => 'SL','countryname'=> "Sierra Leone",'phonecode' => 232),
        array('id' => 196,'flagicon' => 'SG','countryname'=> "Singapore",'phonecode' => 65),
        array('id' => 197,'flagicon' => 'SK','countryname'=> "Slovakia",'phonecode' => 421),
        array('id' => 198,'flagicon' => 'SI','countryname'=> "Slovenia",'phonecode' => 386),
        array('id' => 199,'flagicon' => 'XG','countryname'=> "Smaller Territories of the UK",'phonecode' => 44),
        array('id' => 200,'flagicon' => 'SB','countryname'=> "Solomon Islands",'phonecode' => 677),
        array('id' => 201,'flagicon' => 'SO','countryname'=> "Somalia",'phonecode' => 252),
        array('id' => 202,'flagicon' => 'ZA','countryname'=> "South Africa",'phonecode' => 27),
        array('id' => 203,'flagicon' => 'GS','countryname'=> "South Georgia",'phonecode' => 0),
        array('id' => 204,'flagicon' => 'SS','countryname'=> "South Sudan",'phonecode' => 211),
        array('id' => 205,'flagicon' => 'ES','countryname'=> "Spain",'phonecode' => 34),
        array('id' => 206,'flagicon' => 'LK','countryname'=> "Sri Lanka",'phonecode' => 94),
        array('id' => 207,'flagicon' => 'SD','countryname'=> "Sudan",'phonecode' => 249),
        array('id' => 208,'flagicon' => 'SR','countryname'=> "Suriname",'phonecode' => 597),
        array('id' => 209,'flagicon' => 'SJ','countryname'=> "Svalbard And Jan Mayen Islands",'phonecode' => 47),
        array('id' => 210,'flagicon' => 'SZ','countryname'=> "Swaziland",'phonecode' => 268),
        array('id' => 211,'flagicon' => 'SE','countryname'=> "Sweden",'phonecode' => 46),
        array('id' => 212,'flagicon' => 'CH','countryname'=> "Switzerland",'phonecode' => 41),
        array('id' => 213,'flagicon' => 'SY','countryname'=> "Syria",'phonecode' => 963),
        array('id' => 214,'flagicon' => 'TW','countryname'=> "Taiwan",'phonecode' => 886),
        array('id' => 215,'flagicon' => 'TJ','countryname'=> "Tajikistan",'phonecode' => 992),
        array('id' => 216,'flagicon' => 'TZ','countryname'=> "Tanzania",'phonecode' => 255),
        array('id' => 217,'flagicon' => 'TH','countryname'=> "Thailand",'phonecode' => 66),
        array('id' => 218,'flagicon' => 'TG','countryname'=> "Togo",'phonecode' => 228),
        array('id' => 219,'flagicon' => 'TK','countryname'=> "Tokelau",'phonecode' => 690),
        array('id' => 220,'flagicon' => 'TO','countryname'=> "Tonga",'phonecode' => 676),
        array('id' => 221,'flagicon' => 'TT','countryname'=> "Trinidad And Tobago",'phonecode' => 1868),
        array('id' => 222,'flagicon' => 'TN','countryname'=> "Tunisia",'phonecode' => 216),
        array('id' => 223,'flagicon' => 'TR','countryname'=> "Turkey",'phonecode' => 90),
        array('id' => 224,'flagicon' => 'TM','countryname'=> "Turkmenistan",'phonecode' => 7370),
        array('id' => 225,'flagicon' => 'TC','countryname'=> "Turks And Caicos Islands",'phonecode' => 1649),
        array('id' => 226,'flagicon' => 'TV','countryname'=> "Tuvalu",'phonecode' => 688),
        array('id' => 227,'flagicon' => 'UG','countryname'=> "Uganda",'phonecode' => 256),
        array('id' => 228,'flagicon' => 'UA','countryname'=> "Ukraine",'phonecode' => 380),
        array('id' => 229,'flagicon' => 'AE','countryname'=> "United Arab Emirates",'phonecode' => 971),
        array('id' => 230,'flagicon' => 'GB','countryname'=> "United Kingdom",'phonecode' => 44),
        array('id' => 231,'flagicon' => 'US','countryname'=> "United States",'phonecode' => 1),
        array('id' => 232,'flagicon' => 'UM','countryname'=> "United States Minor Outlying Islands",'phonecode' => 1),
        array('id' => 233,'flagicon' => 'UY','countryname'=> "Uruguay",'phonecode' => 598),
        array('id' => 234,'flagicon' => 'UZ','countryname'=> "Uzbekistan",'phonecode' => 998),
        array('id' => 235,'flagicon' => 'VU','countryname'=> "Vanuatu",'phonecode' => 678),
        array('id' => 236,'flagicon' => 'VA','countryname'=> "Vatican City State (Holy See)",'phonecode' => 39),
        array('id' => 237,'flagicon' => 'VE','countryname'=> "Venezuela",'phonecode' => 58),
        array('id' => 238,'flagicon' => 'VN','countryname'=> "Vietnam",'phonecode' => 84),
        array('id' => 239,'flagicon' => 'VG','countryname'=> "Virgin Islands (British)",'phonecode' => 1284),
        array('id' => 240,'flagicon' => 'VI','countryname'=> "Virgin Islands (US)",'phonecode' => 1340),
        array('id' => 241,'flagicon' => 'WF','countryname'=> "Wallis And Futuna Islands",'phonecode' => 681),
        array('id' => 242,'flagicon' => 'EH','countryname'=> "Western Sahara",'phonecode' => 212),
        array('id' => 243,'flagicon' => 'YE','countryname'=> "Yemen",'phonecode' => 967),
        array('id' => 244,'flagicon' => 'YU','countryname'=> "Yugoslavia",'phonecode' => 38),
        array('id' => 245,'flagicon' => 'ZM','countryname'=> "Zambia",'phonecode' => 260),
        array('id' => 246,'flagicon' => 'ZW','countryname'=> "Zimbabwe",'phonecode' => 263),
        );
         foreach ($countries as $key => $data) {
            CountryModel::create($data);
        }
    }
}
